apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    openshift.io/display-name: LlamaCPP
  name: llamacpp
spec:
  predictor:
    containers:
      - name: llamacpp-container
        image: <oci-name>
        env:
          - name: STORAGE_URI
            value: <s3-location>
          - name: MODEL_PATH
            value: /mnt/models
          - name: HOST
            value: 0.0.0.0
        ports:
          - containerPort: 8000
            name: http1
            protocol: TCP
            hostPort: 8001
        securityContext:
          runAsNonRoot: true
    multiModel: false
    supportedModelFormats:
      - name: any
