name: Build and Push Docker Image to Quay.io

on:
  workflow_dispatch:
      
jobs:
  
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Docker image
        run: docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/model_work:q8 -f CodeLLama.Q8.Dockerfile .

      - name: Push Docker image to Quay.io
        run: docker push quay.io/${{ secrets.QUAY_USERNAME }}/model_work:q8 
