name: Build and Push Docker Image to Quay.io

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Docker image
        run: docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/your-image-name:latest .

      - name: Push Docker image to Quay.io
        run: docker push quay.io/${{ secrets.QUAY_USERNAME }}/your-image-name:latest      
